### ISSUE TITLE
BelongsToMany relationships are immediately deleted on store in one direction

### ISSUE THREAD

**Issue by smallhadroncollider** [analogueorm/analogue#109]
I think this is a result of #71 

I have `Films` and `ProductionCompanies` in a many to many relationship:

``` php
<?php

namespace App\Domain\Entities;

use Analogue\ORM\EntityMap;

class FilmMap extends EntityMap
{
    public function production_companies(Film $film)
    {
        return $this->belongsToMany($film, ProductionCompany::class, "production_companies_films", "film_id", "production_company_id");
    }
}
```

``` php
<?php

namespace App\Domain\Entities;

use Analogue\ORM\EntityMap;

class ProductionCompanyMap extends EntityMap
{
    public function films(ProductionCompany $productionCompany)
    {
        return $this->belongsToMany($productionCompany, FilmSeriesName::class, "production_companies_films", "production_company_id", "film_id");
    }
}
```

If I create a production company, attach some films and then store it, the relationship seems to get stored. However, if I create a film and attach some production companies, the relationships are not stored.

More precisely, when the `Film` entity goes through `Store`, it creates the correct records on the pivot table. But after this the `ProductionCompany` entities also pass through `Store` and when [`$this->aggregate->syncRelationships($foreignRelationships)`](https://github.com/analogueorm/analogue/blob/5.1/src/Commands/Store.php#L145) runs they get deleted again.

This seems to be because nothing gets passed into the [`BelongsToMany::sync()` method](https://github.com/analogueorm/analogue/blob/5.1/src/Relationships/BelongsToMany.php#L606).

I've tried to work it out, but not getting anywhere. Seems to be that when the first entity is saved it would need to add itself to the entities on the other side of the relationship?

**Comment by RemiCollin** [comment]
Yes I guess this could happen if you run store() on both entities, and if the relationship property on the second entity is initialized to `array()` or `null`, in which case the mapper would interpret this as no related records. 

Can you share some code on how the store process takes place ?

**Comment by smallhadroncollider** [comment]
I'm only running store on the `Film` entity. The `film` property of `ProductionCompany` is set to be an `EntityCollection` and the `production_companies` property of `Film` is set to an `EntityCollection` too.

```php
class ProductionCompany extends Entity
{
    public function __construct()
    {
        $this->films = new EntityCollection();
    }
}
```

```php
class Film extends Entity
{
    public function __construct()
    {
        $this->production_companies = new EntityCollection();
    }

    public function addProductionCompany(ProductionCompany $productionCompany)
    {
        // containsEqual is added as a macro to Collection - checks if two entities have
        // the same values for some defined properties
        if (!$this->production_companies->containsEqual($productionCompany)) {
            $this->production_companies->push($productionCompany);
        }

        return $this;
    }

    public function addProductionCompanies(array $productionCompanies)
    {
        foreach ($productionCompanies as $productionCompany) {
            $this->addProductionCompany($productionCompany);
        }

        return $this;
    }
}
```

The code that stores it creates/loads a `Film` entity, then uses `addProductionCompanies` to add a collection of `ProductionCompany` entities then runs `store` on the `Film` entity. It definitely persits the relations initially, but then they're deleted immediately afterwards.

**Comment by smallhadroncollider** [comment]
Looks like `Store` is getting called on the `ProductionCompany` from [`Store:142`](https://github.com/analogueorm/analogue/blob/5.1/src/Commands/Store.php#L140) - calling `$this->createStoreCommand($related)->execute()` as they are dirty related aggregates.

**Comment by smallhadroncollider** [comment]
The relations do persist if I remove the ` $this->films = new EntityCollection()` from `ProductionCompany::__construct()`.

**Comment by RemiCollin** [comment]
I usually use native Collection objects when initializing my entities, so I never runned into these issue. The EntityCollection class surely needs a bit of rework though.
