### ISSUE TITLE
Requested file 'Illuminate\Database\Capsule\Manager' is missing. Execution stopped.

### ISSUE THREAD

**Issue by noescom** [analogueorm/analogue#111]
According to the documentation Analogue is framework agnostic, so I tried to incorporate it in my own MVC framework. It complains: "Requested file 'Illuminate\Database\Capsule\Manager' is missing. Execution stopped". This namespace is part of Laravel, so it seems Analogue can't be used without Laravel?

**Comment by smallhadroncollider** [comment]
It requires a few Laravel packages (Database, Events, Pagination). As long as those are included (which they should be if you used composer to install Analogue) you can use with whatever code you like.

**Comment by RemiCollin** [comment]
Exactly, there are a few dependencies, but you can totally use it without the full laravel framework
