### ISSUE TITLE
Analogue Presenter Repository

### ISSUE THREAD

**Issue by smallhadroncollider** [analogueorm/analogue#113]
I've created a Presenter class (ala [Jeffrey Way's Presenter class](https://github.com/laracasts/Presenter)): https://github.com/smallhadroncollider/analogue-presenter

If you would like to, I'd be happy for it to be added to the Analogue GitHub organisation, then it can use the `Analogue` namespace. Let me know if you'd be happy to do that and I'll setup a transfer request. If not I'll just do it under my own namespace instead.

**Comment by RemiCollin** [comment]
I also use the Jeffrey's package a lot and had been thinking of making an analogue version of it several times. Nice work! No problem for adding it to the organisation, just send the transfer request. Thanks!

**Comment by smallhadroncollider** [comment]
Hmm, I need Admin rights to the organisation apparently.

I've added 0.2.0 which uses the Analogue namespace. You could grab that version and then upload it to the analogue organisation - then you don't need to grant me admin rights.

You'll need to submit it on packagist too. Sorry to give you all the work.

**Comment by RemiCollin** [comment]
ok, no problem, i'll take care of this

**Comment by RemiCollin** [comment]
done !

**Comment by smallhadroncollider** [comment]
Could you add me as a contributor to the repo, then I can push up any changes.

**Comment by RemiCollin** [comment]
Sure!

**Comment by smallhadroncollider** [comment]
Great, thanks :)

**Comment by smallhadroncollider** [comment]
I updated the Packagist namespace to `analogue` rather than `analogueorm` for consistency. Think it needs readding to Packagist to update it. Sorry!

**Comment by RemiCollin** [comment]
It updated to packagist, but didn't seem to change the composer namespace. I guess i'll have to make another entry for it in packagist, trying that.

**Comment by RemiCollin** [comment]
Should be good now !
