### ISSUE TITLE
$with loops

### ISSUE THREAD

**Issue by smallhadroncollider** [analogueorm/analogue#119]
If I have two entity maps:

```
class ScoreMap extends EntityMap
{
    protected $with = ["scoreable"];

    public function scoreable(Score $score)
    {
        return $this->morphTo($score);
    }
}
```

```
class FilmMap extends EntityMap
{
    protected $with = ["score"];

    public function score(Film $film)
    {
        return $this->morphOne($film, Score::class, "scoreable");
    }
}
```

When I try to get a `Score` or a `Film` I think it's creating an infinite loop on the `$with`, as the page never loads and PHP runs out of memory.

**Comment by RemiCollin** [comment]
This was actually happening with Eloquent at the time I forked the library, so it's a known limitation. Not sure how we should handle this as the Relationship object isn't aware of the context. I'll think about this.
