### ISSUE TITLE
Pushing minimum requirements to PHP7 

### ISSUE THREAD

**Issue by RemiCollin** [analogueorm/analogue#126]
Would you mind if the next version of Analogue (5.3) pushes the minimum requirement to PHP7 ?

**Comment by tabennett** [comment]
+1 
I would like to see this. I'm pushing the min requirements up to 7 for the 2.0 release of https://github.com/codesleeve/stapler and I see a lot of other project maintainers starting to do the same.

**Comment by smallhadroncollider** [comment]
+1

Will you back-port general fixes/new tests down to Analogue 5.2? I can't move to Laravel 5.3 for some of my projects as they've got to go on rusty old university servers.

**Comment by RemiCollin** [comment]
Yes I'll backport the new tests and bugfixes, but won't port some of the new features as some of them rely on PHP7.

**Comment by RemiCollin** [comment]
PHP5.6 support will be dropped in 5.4, in order to implement new features which require PHP7
