### ISSUE TITLE
MappableTrait ignores Entity mutators

### ISSUE THREAD

**Issue by jamesmcfadden** [analogueorm/analogue#127]
The `MappableTrait` trait accesses the entity `$attributes` property directly, meaning when using `MappableTrait` methods, any mutators defined on the Entity are ignored.

Example:

```
class User extends Entity
{
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = \Hash::make($value);
    }
}
```

```
$attributes = [
    'email' => 'me@domain.com',
    'password' => 'secret'
];

// user password is not hashed because newInstance uses Entity::setEntityAttributes
$this->mapper->newInstance($attributes);
$this->mapper->store($user); // Oops, unhashed password
```

I understand why this happens - if `getEntityAttribute` were to invoke any `get` mutators, the raw data would be persisted in it's mutated form, which would be incorrect.

So the real problem is that we have no way to populate an entity's attributes with an array that makes use of the entity mutators.

Proposition:

Create a fill method within Entity:

```
public function fill(array $attributes)
{
    foreach ($attributes as $key => $value) {
        $this->__set($key, $value);
    }
    return $this;
}
```

This would allow setting multiple attributes in one go, without ignoring `set` mutators, and would match the current Eloquent API. I'd propose changing `Mapper::newInstance()` to use this new method in place of `setEntityAttributes`.

**Comment by RemiCollin** [comment]
The `MappableTrait` was intended to be used with Plain Objects that didn't extend the `Entity` base class, so it's sole use is for the mapper to fill the object with data, while the object's implementation is left to the user. 

Nevertheless, it's far from perfect and I intend to change this in upcoming `5.3` release. As this version will support direct mapping of plain object using the `Reflection` API, the `MappableTrait` will be deprecated. 

I was thinking of adding some kind of `MagicPropertyTrait` and `MutatorsTrait`, instead which behaviour would be more explicit. What do you think ?

**Comment by jamesmcfadden** [comment]
Reflection based mapping will be a welcome addition. I think all I'm really after with regards to the `Entity` is a way to set an array of attributes that run the `set` mutators on them as the object is filled. We have `Entity::toArray()` which runs `get` mutators, so I think it makes sense to have a `Entity::fill()` (or similarly named) to run the `set` mutators.

With that said, it depends on how you foresee a `MutatorsTrait` working? Would that mimic the mutator functionality in `Entity`?

**Comment by RemiCollin** [comment]
I think it make sense. I added a fill() method that run the mutators to the base `Entity` class. It's just published in latest release.

**Comment by jamesmcfadden** [comment]
Perfect! I'll close this (for reference: #129 fixes).
