### ISSUE TITLE
Mappers are not serializable.

### ISSUE THREAD

**Issue by tabennett** [analogueorm/analogue#132]
Currently, it's not possible to store an instance of a class that uses `Analogue\ORM\System\Mapper` (as a class variable ) inside of Job and have be called from the dispatcher.

This seems to be caused by the fact that the mapper class holds reference to many other objects that contain instances of `Closure` (such as the `$dispatcher`, `$adapter`, etc variables) and so the `Queue` class is choking when it tries to serialize those. Unless I'm missing something here, this essentially means that we can't use (store as a variable on the class) anything that contains an instance of the mapper, such as repositories, etc. So if I have a job that's using a repository, I can't use dependency injection in the constructor to inject my repositories as store them in class variables so they'll be there when `handle()` is called.

**Comment by RemiCollin** [comment]
You can workaround this by using method based injection : 

```
class Job 
{
     protected $user;

     public function __construct(User $user)
    {
        $this->user = $user;
    }

    public function handle(UserRepository $userRepository)
    {
        ...
    }
}
```

**Comment by tabennett** [comment]
Yeah, this just caught me off guard. It might be worth putting a warning or something about this in the docs later on down the road. Thank you for your help.

**Comment by RemiCollin** [comment]
The doc needs a complete rewrite anyway, and I plan to move it from the wiki to a dedicated site for 5.3 release.
