### ISSUE TITLE
(Feature Request) orderBy property on EntityMaps

### ISSUE THREAD

**Issue by smallhadroncollider** [analogueorm/analogue#134]
Is it possible to provide a property along the lines of `protected $orderBy = ["name", "ASC"];` to EntityMaps to provide default sorting order for queries?

**Comment by RemiCollin** [comment]
You mean to provide default sorting on relationship queries ?

**Comment by smallhadroncollider** [comment]
Yes. At the moment if I want to order records by, say, the name column (rather than id) I have to remember to add a sort query in my Repository as well as adding a method to my Entity to return a sorted version of any relationships (and then remember to use the method).

**Comment by RemiCollin** [comment]
I never tried it myself, but you should be able add the `orderBy` method in your EntityMap's relationship method : 

```
    public function users(Role $entity)
    {
        return $this->hasMany($entity, App\User::class)->orderBy('name', 'asc');
    }
```

**Comment by RemiCollin** [comment]
Closing this as this is possible to use orderBy() since 5.5 release
