### ISSUE TITLE
NeoEloquent integrations

### ISSUE THREAD

**Issue by m33ch** [analogueorm/analogue#136]
Hi all,

one question, this package is compatible with [NeoEloquent](https://github.com/Vinelab/NeoEloquent) package? 

If yes, how to configure?

Thank you very much!

**Comment by RemiCollin** [comment]
Righ now it's not compatible with this package. I'm currently working on a MongoDB bridge based on https://github.com/jenssegers/laravel-mongodb , so i'd say that a Neo4j bridge which would interface with NeoEloquent's query builder should be possible, still not planned yet.
