### ISSUE TITLE
Problem after the commit "EntityCollection are now keyed by Entity primary key"

### ISSUE THREAD

**Issue by vovanmix** [analogueorm/analogue#138]
Hi!
I use the result that I get from the ORM to encode it right away to JSON. And `json_encode` automatically encodes PHP arrays that do not have consecutive numeric keys as objects, instead of arrays. And now when EntityCollection always return keys as IDs, it's very inconvenient because I get JSON objects by default. Is it possible to make key as a primary key optional?
Thank you!

**Comment by RemiCollin** [comment]
Hello! Thanks for reporting this. It's obviously a non-desired side effect. I guess we can override the toJson() method to unkey the collection before returning it, so we'll have best of both worlds.

**Comment by vovanmix** [comment]
This might not help in all the cases. For example, in some of my use-cases I take an array from the ORM, make some processing and pass in to a third-party lib to make a JSON response. It would be great if I just can get an un-keyed array from the ORM by using some option. And IMHO the default behavior should be to return an un-keyed array, and to get id-based keys we can pass/set an option.

**Comment by RemiCollin** [comment]
I agree it shouldn't returned either keyed array when converting array or json.

Does it work for you : https://github.com/analogueorm/analogue/commit/8ced7ea010003a86a544f6f6e3352127100465c9 ?

**Comment by vovanmix** [comment]
Nice, thank you, I will try on following days and let you know!
