### ISSUE TITLE
(Feature Request) Ability to map entity attributes to column names

### ISSUE THREAD

**Issue by rickycheers** [analogueorm/analogue#142]
We're implementing DDD on a legacy project where the column names of the database tables don't follow a consistent naming convention. We're now, trying to work around this issue by modeling the properties of our entities in a more consistent way.

In a use case like this, it would be nice if we could map a property of an entity with a given table column.

Example:

Table Structure
```
Table: leads
Columns:
- ID
- First_Name
- Last_Name
- email_address
```
Entity Class
```php
class Lead
{
  protected $id;
  protected $firstName;
  protected $lastName;
  protected $email;

// or

  protected $attributes = [
    'id',
    'firstName',
    'lastName',
    'email'
  ]
}
```
Entity Mapping
```php
class LeadMap extends EntityMap
{
    protected $table = "leads";
    protected $primaryKey = "ID";
    public $timestamps = false;
    protected $attributes = [
        'firstName' => 'First_Name',
        'lastName'  => 'Lirst_Name',
        'email' => 'email_address'
    ];
}
```
Are there any plans to achieve something like this?

I would love to try to contribute something if pointed in the right direction.

Regards!

**Comment by RemiCollin** [comment]
This should be fairly easy to implement. Attribute transformation takes place in 2 methods :

- Entity -> DB : Analogue\System\Aggregate::getRawAttributes()
- DB -> Entity : Analogue\System\EntityBuilder::build()

We can use the $attributes property of the entityMap for this, but it should be in this form :

```
    protected $attributes = [
         'column_in_db' => 'entity_property',
    ];
```

Don't hesitate if you have any question
