### ISSUE TITLE
How to log all queries

### ISSUE THREAD

**Issue by vovanmix** [analogueorm/analogue#143]
Hi!
I don't use Laravel and trying to user this ORM as a primary access to the database. I want to log all my queries. In Laravel I can do 
```php
 DB::listen(function ($query) {
            // $query->sql
            // $query->bindings
            // $query->time
        });
```
How can I do the same with Analogue?
If I try to so something like this:
```php
$db = \Analogue\ORM\Analogue($conf);
$db->listen(function ($query) {
  var_dump($query->sql);
});
```
nothing gets logged. There's no errors also, so I assume that method `listen` exists but is not working.
Thanks!

**Comment by RemiCollin** [comment]
Calling directly $db listen would redirect on Analogue manager, not on Capsule DB. 

Try this `$db->connection()->listen` instead

**Comment by vovanmix** [comment]
That works, thanks!
One more necessary step though:
```php
$db->connection()->setEventDispatcher(new \Illuminate\Events\Dispatcher(new \Illuminate\Container\Container));
```
