### ISSUE TITLE
Can't create mapper - Unsupported driver

### ISSUE THREAD

**Issue by Sufir** [analogueorm/analogue#149]
> illuminate/database v5.3.23
> analogue/orm v5.3.2

I'm using Analoue without Laravel:

```
        $options = $container->get('config');

        $analogue = new Analogue\ORM\Analogue([
            $options['db']['core']
        ]);

        foreach ($options['db'] as $name => $config) {
            $analogue->addConnection($config, $name);
        }
```

Query builder working:
```
        $analogue->connection('some-name')->select...
```

If try create mapper, I see error `Unsupported driver []` in DatabaseManager.
```
        $analogue->mapper(User::class, UserMap::class);
```

**Comment by RemiCollin** [comment]
Is the `connection` property set to any of your registered connection in your `UserMap` ?  If not the DatabaseManager would attempt to load the connection named `default`, which is probably what is happening here.

**Comment by Sufir** [comment]
Oh, I don't seen these parameter. Sorry.
