### ISSUE TITLE
BelongsToMany results missing from eager-loaded nested relations

### ISSUE THREAD

**Issue by hexus** [analogueorm/analogue#171]
@devsi and I have started using this library and it's truly fantastic.

However, we've encountered an issue with the `BelongsToMany` relation when it's eagerly loaded as a nested relation. I imagine this _might_ be an issue with the version of Eloquent you forked, after some investigation, but I can't be certain.

It would be nice to know whether this is actually a bug, or whether we're doing something wrong.

---

Here are the relations in our system:
- **Quizzes** _many to many_ **Questions**
- **Questions** _one to many_ **Options**

We have one Quiz, with three Questions, each having a number of Options.

If we eagerly load Options with their parent Questions, as well as the Quizzes of those Questions like so:

```php
$options = $optionMapper->with('question.quizzes')->get();
```

It ends up that only the last pivot for Quizzes is actually taken into account, seemingly because all of these will be the *same* Quiz (ID 1).

**Here's the result set with eager loading**:

https://pastebin.com/0FC1Vb88

Here, only the last loaded Quiz pivot is included.

**Here's the correct result set with lazy loading**, or if we only eager load questions (`with('question')`):

https://pastebin.com/sGBM01qY

Here, all the pivots are loaded properly without eager loading.

---

If need be, I can make these result sets much simpler and even provide the queries run, but I thought I'd just outline it for time being to see if you knew about this.

I traced to the `BelongsToMany::match()` method having a dictionary with a single item, instead of three.

When `System\Query::loadRelation()` is run for this relationship, the `$results` collection indeed only contains the last pivot, but if I run the corresponding SQL result manually on my database, the results include all three.

Cheers!

**Comment by RemiCollin** [comment]
Is it happening in the `5.4` version of Analogue ? I have refactored the Eager loading in `dev-master`, (which is upcoming `5.5` version), can you tell me if it is happening with this version as well ?

**Comment by hexus** [comment]
Yes, we were using the 5.4 version. I'll check with dev-master now.

**Comment by hexus** [comment]
Just noticed another issue too, where `BelongsToMany` fails on a classic `User` to `Group` relation if `Group` has a different `$primaryKey` value - ours is `groupid` due to legacy reasons.

This *is* with our custom connection, so I was going to swap back to the built in Illuminate one to see if that was the problem too. I'll let you know what I find.

**Comment by RemiCollin** [comment]
Yes `5.5` requires PHP7, as the proxy generation is delegated to the (awesome) `ocramius/proxy-manager` library which requires PHP7. Also laravel 5.5 will require PHP7 so I thought it was a good timing to introduce it. 

Anyway I'll look into it as it's more likely to be a `Relationship` issue than the eager loading process itself. 

For your other issue, you should be able to customize the foreign key for the relationship in the `->belongsToMany()` method, and feel free to open another thread on here if it doesn't work ;)

**Comment by hexus** [comment]
From `->belongsToMany()` all I can change are the keys on the pivot table, whereas the primary key I was referring to is on the `GroupMap`. 

I shall open a separate issue for it. Cheers. :)

**Comment by hexus** [comment]
Yeah, I just tried with `dev-master` and I'm getting the same issue as above.

**Comment by RemiCollin** [comment]
Possibly related to #172

**Comment by RemiCollin** [comment]
After investigating, this is exactly the same bug as the other issue you're described. There's something wrong in the code that is generating the eager loading dictionnary in the `BelongsToMany` class. I'm working on a fix, workaround for now is to use lazy loading.

**Comment by hexus** [comment]
Awesome! I'm glad it's one bug rather than two in that case. :) Thank you for looking into this.

**Comment by RemiCollin** [comment]
Just published a fix https://github.com/analogueorm/analogue/pull/174

Can you confirm it works for you ?

**Comment by hexus** [comment]
I'll be able to confirm this tomorrow. Cheers! :+1:

**Comment by hexus** [comment]
By "tomorrow" I meant Monday. 😁

I've just tested 5.4.1 with the same code as before and it works like a charm.

Thank you for fixing this so swiftly, it's very much appreciated!
