### ISSUE TITLE
What is the best way to 'detach' a relation? (in my case, belongsToMany)

### ISSUE THREAD

**Issue by devsi** [analogueorm/analogue#182]
Hi Remi,

I have a many to many relationship set up through a pivot table and i'm looking for a way to delete the row from the pivot table to detach the 2 related models.

So you have an idea of the relation:

> 
> 	public function questions(Analogue\Quiz $quiz)
> 	{
> 		return $this
> 			->belongsToMany($quiz, Analogue\Question::class, 'quiz_question_junction', 'quiz_id', 'question_id')
> 			->withPivot(['sort_order', 'created_date']);
> 	}
> 

A **quiz** has many **questions**, and a **question** can have many **quizzes**.

Is there a way to do this through Analogue? I see in `BelongsToMany()` a detach method, but I can't figure out how to use it, or if it can be used in this instance.

Thanks :)

**Comment by devsi** [comment]
Alright actually hold up. @hexus found the solution in your test cases:

https://github.com/analogueorm/analogue/blob/5.4/tests/cases/Relationships/BelongsToManyTest.php#L161

Unless you suggest a different way, I'll consider this the correct way :)

**Comment by hexus** [comment]
😁 👍
