### ISSUE TITLE
What's the best way to count a relation without loading the Entities?

### ISSUE THREAD

**Issue by hexus** [analogueorm/analogue#183]
I've been trying to understand, with @devsi, how to load the count of a related Entity without loading the related entities themselves.

I know there's a `getRelationCountQuery()` on Relationships, but I'm not sure what the two Query arguments need to be.

**Comment by hexus** [comment]
An approach I've discovered is as such, but I'm still wondering if there's a better way; one that doesn't require me to retrieve the foreign key myself.

```php
$quizMapper = $analogue->mapper(Quiz::class);
$relation = $quizMapper->getRelation('questions');
$relation->whereIn($relation->getForeignKey(), [1, 2, 3])->count()
```

**Comment by RemiCollin** [comment]
I think the best way would be to implement this in the `CollectionProxy` class, this way, calling the `count()` method would simply execute a `count` query, leaving the relation ship unloaded. Was planning this for the 5.5 version as long with other optimized methods such as `pluck()`, but I guess we could totally implement this on the 5.4 version, as the impact on client code should be minimal.

**Comment by RemiCollin** [comment]
(sorry for my lack of reactivity, i'm on vacation this month)

**Comment by hexus** [comment]
Cool! I look forward to it. Until then I'm sure I'll manage in userland. :)

I assumed you might be, no worries at all. Enjoy your time off!

**Comment by Insolita** [comment]
> I think the best way would be to implement this in the CollectionProxy class, this way, calling the count() method would simply execute a count query, leaving the relation ship unloaded. Was planning this for the 5.5 version as long with other optimized methods such as pluck(), but I guess we could totally implement this on the 5.4 version, as the impact on client code should be minimal.

It's very interesting, but not clear how to do this feature.. is it already supported?

**Comment by RemiCollin** [comment]
Added in v5.6.1

**Comment by hexus** [comment]
Awesome! Cheers.
