### ISSUE TITLE
Nested Entities and Value Objects

### ISSUE THREAD

**Issue by mitjarobic** [analogueorm/analogue#19]
Hello, 

could you please provide an example or a guideline for solving this kind of problem? 

Ty

**Comment by RemiCollin** [comment]
Can you please be more specific ? 

What are you trying to achieve ?

**Comment by mitjarobic** [comment]
Order is Entity, Money and Currency are VOs ... 

```
new Order($userId, new Money(100, new Currency('EUR')))
```

in Money VO i have...

```
 public function setEntityAttribute($key, $value)
    {

        if($key=='currency'){
            $value = new Currency($value);
       }

        $this->attributes[$key] = $value;
    }
```

is this the right approach? How would i solve the problem if Currency needed two or more attributes in constructor?

**Comment by mitjarobic** [comment]
one more thing... how would i store a custom pivot column on a Many to Many relationship?

**Comment by RemiCollin** [comment]
Nested entities are not supported yet, i'm working on them so they should be available in 2.2. You can use the method you described as a workaround for now. 

To set a custom pivot table, just pass it as a third argument in the relationship method :

```
return $this->belongsToMany($user, 'App\Resource', 'custom_table');
```

**Comment by mitjarobic** [comment]
I meant a column on a pivot table not the name for a pivot table... this is an example for an 'expires' attribute on a pivot table from L5 docs... how would i do that?
```
$user->roles()->attach(1, ['expires' => $expires]);
```

**Comment by mitjarobic** [comment]
I meant a column on a pivot table not the name for a pivot table... i can get the column from the pivot table, but i dont know how to set it...

```
return $this->belongsToMany($user, 'App\Role', 'custom_table')->withPivot("expires");
```

this is an example for an 'expires' attribute on a pivot table from L5 docs... how would i do that?

```
$user->roles()->attach(1, ['expires' => $expires]);
```

**Comment by RemiCollin** [comment]
When a Many-to-many relationship is stored, a pivot attributes is added to the related entity. 

You access it like this :

```
$user->roles->first()->pivot->expires
```

This behaviour is inherited from Eloquent, but it's less than ideal in Analogue, as the Pivot is only created on store, you can only set pivot attributes on update. 

A better way is to use a custom UserRole entity for the intermediate table (using hasMany relationships between the pivot table and the two sides of the relationship), which is what doctrine does. I'll see how we can streamline/simplify this in a future version.
