### ISSUE TITLE
Generation of primary key value (e.g. using UUID)

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#20]
I'm looking for a way to create the primary key value when creating a new entity. Something like this:
```php
$entity = new MyEntity;
print $entity->id; // "550e8400-e29b-11d4-a716-446655440000"
```
It would be nice to have a primary key generated before the entity gets saved to the database.
At present if I modify the `id` property *by hand* the StateChecker complains about it.

What's the best way to achieve this? Thanks!

**Comment by RemiCollin** [comment]
You're right we should be able to set custom primary keys value.

Unknown id's in the cache are now treated as new Entities so you should be able to use custom set uuid's as primary keys.

**Comment by thasmo** [comment]
Awesome, thanks a lot for the fast reaction! Gonna test it soon.

**Comment by thasmo** [comment]
@RemiCollin, works like a charm, thanks!

**Comment by RemiCollin** [comment]
Great ! :)
