### ISSUE TITLE
Storing entity converts primary key to integer

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#21]
When storing an entity the primary key gets converted to an integer which destroys the key's value if it's a string e.g. a UUID. I'm not sure where this happens, I can't find where it get's converted.

**Comment by thasmo** [comment]
The entity gets stored correctly in the database with the UUID as primary key, but the entity returned by `$entity = $repo->store($entity)` has it's primary key converted to `int`.

**Comment by thasmo** [comment]
Seems like the Illuminate Query Processor tries to get the last insert ID (which is '0'), and returns it [here](https://github.com/analogueorm/analogue/blob/v2.1.8/src/Commands/Store.php#L645). Is this an Illuminate problem or a Analogue bug related to the introduction of custom primary keys?

**Comment by RemiCollin** [comment]
I guess this is indeed related to Illuminate and happens when insertGetId is called.

Is your UUID column is defined as primary key ?

**Comment by thasmo** [comment]
Yes, it is. I think MySQL just won't return a `last inserted ID` because the primary key field is, intentionally, not `auto incrementing` - as I set the value manually when creating the entity.

Would a change to the insert method like this, work:
```php
protected function insert()
{
	$entity = $this->entity;
	$attributes = $this->getRawAttributes();
	$keyName = $this->entityMap->getKeyName();

	if(isset($attributes[$keyName])) {
		$id = $this->query->insertGetId($attributes);
		$entity->setEntityAttribute($keyName, $id);
	} else {
		$this->query->insert($attributes);
	}
}
```

**Comment by RemiCollin** [comment]
Ok, just published a fix on the dev-master branch. Can you try it and confirm me it works ?

**Comment by thasmo** [comment]
@RemiCollin, works! The primary key won't get overwritten if the primary key has been set on the entity manually. :)

**Comment by thasmo** [comment]
Thanks for the quick fix.

**Comment by RemiCollin** [comment]
Welcome !
