### ISSUE TITLE
Undefined variable: factory

### ISSUE THREAD

**Issue by Insolita** [analogueorm/analogue#217]
$factory variable definition missing if $proxyPath is null
https://github.com/analogueorm/analogue/blob/b91fd2417dc642d3c9d8c7c262061e69ba2f513b/src/System/Proxies/ProxyFactory.php#L65

**Comment by RemiCollin** [comment]
Fixed

https://github.com/analogueorm/analogue/pull/220/commits/eb9041850a2423446a7ff0b3c5dbd6c849a4e74f
