### ISSUE TITLE
Eager-loading problems

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#22]
I've got a custom Repository class:
```php
class Repository extends AnalogueRepository {
	public function with(array $relations) {
		return $this->mapper->with($relations);
	}
}
```

When I use `$entity = $repository->with(['relation'])->find($id);` it works as expected, but when I use `$repository->with(['relation'])->firstMatching(['attribute' => $value])` it fails with this error:
```
Call to undefined method Illuminate\Database\Query\Builder::firstMatching()
```

Do I have to implement the eager loading myself or in another way to get eager loaded relations using `firstMatching` etc. ?

**Comment by thasmo** [comment]
I guess the problem is that I'd like to use method chaining for my repositories but I'm probably doing it wrong. Does somebody know how I can achieve this?

**Comment by RemiCollin** [comment]
The Analogue repository doesn't implements method chaining. There's an example of repository for eloquent that does it on this blog : http://bosnadev.com/2015/03/26/using-repository-pattern-in-laravel-5-eloquent-relations-and-eager-loading/ . 
I don't fully agree with this approach as It implies that your client code is aware of the underlying query builder, which is not quite right if you want a strict separation of concerns.
