### ISSUE TITLE
Bug or not correctly wiring?

### ISSUE THREAD

**Issue by quarkmarino** [analogueorm/analogue#23]
Don't know exactly where to ask for help in this situation, I think docs should be more comprehensive, I mean, to show better how to wire things up with usual current MVC implementantions, or show what pieces are axactly to be replaced and how. Would help us to make the "mental shift" from pure MVC to correct DDD), I'm still grasping the entity and value objects concepts, and the implementation is getting off of my hands, i'm not sure if not connecting things right or just library bug, for example from:

```php
namespace App\Repositories\Todo;

use Analogue\ORM\Repository;
use App\Entities\Todo;

class TodoRepository extends Repository{    //compacted for brevity
    public function __construct(){
        parent::__construct(Todo::class);
    }
    ...
}
```
I got

    FatalErrorException in Manager.php line 128:
    Call to a member function mapper() on null

    1. in Manager.php line 128
    2. at FatalErrorException->__construct() in HandleExceptions.php line 131
    3. at HandleExceptions->fatalExceptionFromError() in HandleExceptions.php line 116
    4. at HandleExceptions->handleShutdown() in HandleExceptions.php line 0
    5. at Manager::getMapper() in Repository.php line 35
    6. at Repository->__construct() in TodoRepository.php line 21

Any advise, or bug fix from here?

**Comment by thasmo** [comment]
Code looks good, imo. My repositories also look like yours:
```php
class ChannelRepository extends Repository {
	public function __construct() {
		parent::__construct(Channel::class);
	}
}
```
Seems like `Analogue\ORM\System\Manager` wasn't instantiated/initialized correctly for some reason. Can't see why this wouldn't work. You probably needa wait for @RemiCollin to help you out.

**Comment by quarkmarino** [comment]
Thank you, gonna check on the initialization you mention.

**Comment by thasmo** [comment]
@quarkmarino, I meant that Analogue doesn't initialize/instantiate the manager correctly, I guess. Which PHP version do you use btw.?

**Comment by quarkmarino** [comment]
@thasmo, I'm using standard homestead instalation from laravel docs, PHP 5.6.7 to be exact.

Sorry to say this, but it was my bad, terribly terribly bad, I just forgot to add the service provider to my laravel application config, Thanks a lot @thasmo.

**Comment by thasmo** [comment]
Sure, no problem. :)
