### ISSUE TITLE
The problem with storing entity with embedding object

### ISSUE THREAD

**Issue by Insolita** [analogueorm/analogue#231]
I add in FilterTaskMap

```php
 public function stage(FilterTask $task)
    {
        return $this->embedsOne($task, WorkStage::class, 'stage')
            ->setPrefix('')->setColumnMap(['value'=>'stage']);
    }
 
```

And got fails when try test wth storing  (test with finding passed successfull and this embed was resolved)

![ormerror](https://user-images.githubusercontent.com/1847402/32099813-77380f76-bb44-11e7-857b-7229a85faae6.png)

WorkStage is simple stdClass ValueObject (Also WorkStageMap exists, and test wtih finidng was passed)

I'll take a more detailed research a bit later

**Comment by Insolita** [comment]
Made test for entity without relations, only with embededObjects and got same bug;

**Comment by RemiCollin** [comment]
It was actually a regression caused by the last fix. Should be ok now

**Comment by Insolita** [comment]
Hurray!
