### ISSUE TITLE
Carbon::toString() fails when updating an entity

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#24]
I get the error `Call to undefined method Carbon\Carbon::toString() in /vendor/analogue/orm/src/ValueObject.php on line 153` when updating an entity. Carbon has a method `__toString()` but I can't find `toString()`.

Any ideas?

**Comment by thasmo** [comment]
Changing it to `$attributes[$key] = $attribute->__toString();` seems to work. Or do I miss something here?

**Comment by mitjarobic** [comment]
I have the same problem.

**Comment by RemiCollin** [comment]
I'm looking into it

**Comment by RemiCollin** [comment]
fixed in 2.1.0 release
