### ISSUE TITLE
updating an entity

### ISSUE THREAD

**Issue by mitjarobic** [analogueorm/analogue#25]
to illustrate  the problem i have two tests...

```
     /**
     * @test
     */
    public function it_creates_a_user()
    {
        $userMapper = \Analogue::mapper(User::class);
        $user = new User(new Identity('first name', 'last name'));
        $userMapper->store($user);
        $user = $userMapper->find(1);
        $userMapper->store($user);
    }

    /**
     * @test
     */
    public function it_updates_a_user()
    {
        $userMapper = \Analogue::mapper(User::class);
        $user = $userMapper->find(1);
        $userMapper->store($user);
    }

```

first one is ok, second one (record with id 1 exists in database ) fails with the message:

Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such column: first_name (SQL: update "users" set "first_name" = first name, "last_name" = last name where "id" = 1)

**Comment by RemiCollin** [comment]
Is Identity a Value Object ? How is it configured in your Entity Map ?

**Comment by mitjarobic** [comment]
IdentityMap.php:

```
use Analogue\ORM\ValueMap;

class IdentityMap extends ValueMap
{
    protected $attributes = ['first_name', 'last_name'];
}
```

UserMap.php:

```
use Analogue\ORM\EntityMap;

class UserMap extends EntityMap {

    protected $table = 'users';

    protected $embeddables = ['identity' => Identity::class];

}
```

Identity.php:

```
use Analogue\ORM\ValueObject;

class Identity extends ValueObject {

    public function __construct($firstName, $lastName)
    {
        $this->first_name = $firstName;
        $this->last_name = $lastName;
    }

}
```

User.php

```
use Analogue\ORM\Entity;

class User extends Entity {

    public function __construct(Identity $identity)
    {
        $this->identity = $identity;
    }

}
```

**Comment by RemiCollin** [comment]
Are your column correctly named identity_first_name and identity_last_name in the database ?

**Comment by mitjarobic** [comment]
Yes, it works like it should in the first test

**Comment by RemiCollin** [comment]
No, I tried to replicate exactly what you did, i don't get any error. Must be something else. Are your IdentityMap and UserMap classes in the same namespace as the corresponding entity. I suspect one of them is not registered / detected correctly.

**Comment by mitjarobic** [comment]
i pushed my example here https://github.com/mitjarobic/analogue-example

Its a fresh Laravel 5 installation

All classes are in the App namespace. Code should produce the error.

**Comment by RemiCollin** [comment]
Thanks! I'll have a look.

**Comment by mitjarobic** [comment]
did u get the error?
