### ISSUE TITLE
Delete command doesn't return anything

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#26]
Executing `$repository->delete($entity)` doesn't return anything. Wouldn't it be nice to have it return `TRUE` on success?

What I wanted to do is this:
```php
if(!$repository->delete($entity)) {
	return response(NULL, 500);
}
```
For now this doesn't work because it doesn't return any value.

What do you think?

**Comment by RemiCollin** [comment]
Make sense, I'll add it in the next batch.

**Comment by likemusic** [comment]
Why not throw Exception? I wonder what others ORM are doing in this case?

**Comment by unkind** [comment]
Throw runtime exception in case of failure, don't return anything. Once you type `return bool`, it means that you have to check return value **every time**. It means that you either would copy-paste the same code with check, or you would ignore an error. 

Returning `500 Internal Server Error` in case of uncaught exception is responsibility of the Front Controller.

**Comment by RemiCollin** [comment]
I agree with unkind on this. In that case, we can assume that if no exceptions is raised, record is successfully deleted.  

Client code check could be implemented like this : 

```
try {
    $repository->delete($entity);
}
catch (\Exception $e) {
    return response(NULL, 500);
}
```
