### ISSUE TITLE
Is it possible to have properties of entity in camelCase, but fields in DB are in snake_case?

### ISSUE THREAD

**Issue by dajnz** [analogueorm/analogue#263]
Is this auto mapping between names  possible?

**Comment by RemiCollin** [comment]
This is not possible yet, but having control on the attributes/properties name when hydrating/dehydrating entities would be a really good feature. I'd gladly accept a PR regarding this.

**Comment by adrorocker** [comment]
I made a PR [#275] that make this possible @RemiCollin can you take a look at it when possible? 

Thanks 😃

**Comment by adrorocker** [comment]
@dajnz This is now possible if you set `$camelCaseHydratation` to true on the entity map just like :

```php
protected $camelCaseHydratation = true;
```

Late, but hope this help you.
