### ISSUE TITLE
SoftDeletes not working

### ISSUE THREAD

**Issue by defektrain** [analogueorm/analogue#268]
Hello,
Laravel 5.6 and Analogue 5.6.8 and PostgreSQL.

I have an issue with using softDeletes, for example:
```
class User extends Entity 
{ 
}
```

```
class UserMap extends EntityMap
{
    public $softDeletes = true;
} 
```

And a table in DB with fields `id`, `login` and `deleted_at` (timestamp).

When I try to delete:
```
$mapper = mapper(User::class);
$user = $mapper->find($id);
$mapper->delete($user);
```
I get next error:
```
Analogue \ ORM \ Exceptions \ EntityMapNotFoundException
No Map registered for Analogue\ORM\Events\Deleting

…/vendor/analogue/orm/src/System/Manager.php459
```

Can you help me with that? Thanks.

**Comment by RemiCollin** [comment]
Thank you for reporting it; i just released a patch that should fix it; can you run `composer update` and confirm it works for you ?

**Comment by defektrain** [comment]
Yes, now it's working, thank you.
