### ISSUE TITLE
FatalErrorException in EntityMap.php line 593: Call to a member function mapper() on null

### ISSUE THREAD

**Issue by Evertt** [analogueorm/analogue#27]
This is my folder structure:

    app /
        Model /
            Entities /
                Actor.php
                Person.php
            Mappers /
                ActorMap.php
            Repositories /
                ActorRepository.php
                Repository.php

`ActorRepository` extends the abstract `Repository` class which of course extends `Analogue\ORM\Repository`. And in my `AppServiceProvider` I register all the necessary entities and mappers. But when I run the code I get the error that's in the title of this thread.

It all seems to go wrong after it's calling the belongsTo method in my ActorMap, which looks like this:

    public function person(Actor $actor)
    {
        return $this->belongsTo($actor, Person::class);
    }

Can anybody tell me what's going wrong?

**edit:** the error seems to go away when I move the mappers in the same folder and namespace as the entities. But I like to have them separate... :-(

**Comment by mitjarobic** [comment]
Do you use  Analogue::register() method?

https://github.com/analogueorm/analogue/wiki/Configuring-Entity-Maps

**Comment by Evertt** [comment]
Yes, I put this in the boot-method of the AppServiceProvider and thought it should work:

		$entities = glob(app_path() . '/Model/Entities/*.php');

		foreach($entities as $entity)
		{
			$entity = basename($entity, '.php');

			$entityClass = "App\\Model\\Entities\\$entity";
			$mapperClass = "App\\Model\\Mappers\\{$entity}Map";

			if (class_exists($mapperClass))
			{
				Analogue::register($entityClass, $mapperClass);
			}
			else
			{
				Analogue::register($entityClass);
			}
		}

I tested that code and it correctly listed all the Entities and extracted the right class-names and called the register method on those that had a mapper.

**Comment by Evertt** [comment]
Hey Rémi, I see that this commit is not in the new 5.1 branch.
Could you put it in there as well?
