### ISSUE TITLE
Eloquent 5.7

### ISSUE THREAD

**Issue by elvispdosreis** [analogueorm/analogue#278]
is there any provision for support for eloquent 5.7?

**Comment by adrorocker** [comment]
We aim for that next, but PR are welcome.

**Comment by evnix** [comment]
laravel 6 support?

**Comment by adrorocker** [comment]
@elvispdosreis Unfortunately since lack of spare time I was not able to update the library to support 5.7.

On the other hand @evnix, there is a new release that supports Laravel 6.0
