### ISSUE TITLE
Hidden attributes

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#3]
Would be nice to hide attributes (similar to what Eloquent does) by setting a `$hidden` attribute on the EntityMap, which prevents certain methods to provide those hidden attributes.

**Comment by RemiCollin** [comment]
I agree this is a very uselful feature, but as these methods are on the entity itself (toArray(), toJson, etc...), wouldn't it make more sense for the hidden attribute to be defined on the Entity class, than on the EntityMap ?

**Comment by thasmo** [comment]
@RemiCollin, not sure. I thought that maybe the EntityMap is responsible for *configuring* the Entity and the Entity itself is just a simple *shell* for the data, just like all relationships are also defined on the EntityMap and not the Entity itself.

**Comment by thasmo** [comment]
Also because the EntityMap class already has a hidden attribute and a `getHiddenAttributes` getter. Are they unused for now?

**Comment by RemiCollin** [comment]
Yes it's a remain of a previous iteration, it's not implemented. 

Will have a look to see how it can be achieved.

**Comment by RemiCollin** [comment]
Supported in Version 2.1 : Base Entity class now supports hidden attributes
