### ISSUE TITLE
Hidden attributes are ignored on attributes which have get mutators

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#32]
Attributes which have a get mutator will be returned even if they're configured to be hidden. I've commented it in the related commit which introduced the bug in the Entity class [here](https://github.com/analogueorm/analogue/commit/f4bc1c518764dd54c535af59938a5ce7174037b1#diff-822f133f74176a0c31a81e96c610f5fbL106).

**Comment by RemiCollin** [comment]
That's right, nice catch!

**Comment by thasmo** [comment]
Have created a [pull request](https://github.com/analogueorm/analogue/pull/36).

**Comment by thasmo** [comment]
Pull request has been merged.
