### ISSUE TITLE
Illuminate 5.1 packages

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#35]
Is it possible to use Laravel/Lumen 5.1 LTS i.e. the Illuminate 5.1 packages? For now 5.0.* is defined as the only compatible version in composer.json.

**Comment by RemiCollin** [comment]
Yes, I changed the requirement to 5.0.* as there are some breaking changes in 5.1 which need to be handled in a separate branch, as simply updating the whole package to support 5.1 would break the 5.0 apps.

**Comment by thasmo** [comment]
Thanks for your reply. Do you have any plans on supporting Laravel/Lumen 5.1?

**Comment by RemiCollin** [comment]
Yes, definitely.

**Comment by Evertt** [comment]
Would you like some support in this? I really want this to move forward so I'd like to contribute. If you create a new branch for 5.1 support then I'd love to send you some pull-requests. :-)

**Comment by RemiCollin** [comment]
Sorry for the delay. Implemented L5.1 compatibility in 5.1 branch. You'll need to update your composer.json to reflect this.

**Comment by Evertt** [comment]
Awesome, thank you!
Do you plan on continuing to work on Analogue to improve it further? I don't mean to put any pressure on you, I just really like Analogue and I would like to see it evolve. :-)

**Comment by RemiCollin** [comment]
Yes, i'll continue to make it evolve in my spare time :) 

I'm working on a more comprehensive & user-friendly document at the moment, which i think is lacking.

I'd like to implement MongoDB support as well, among some general improvement to the package itself.

**Comment by Evertt** [comment]
Would you be interested in someone to collaborate with? I'd like to contribute to this project; also in my spare-time, so without a schedule. :-)

**Comment by RemiCollin** [comment]
Sure, contributions are more than welcome. 

I need to make some guidelines about this as we have to maintain several branches, corresponding to Illuminate framework versions (5.0 & 5.1 for now), so this make things like new feature integration a bit more complex.

**Comment by RemiCollin** [comment]
@Evertt : do you have a contact address where i can reach you ? ;)

**Comment by Evertt** [comment]
Yes, it's ecvanbrussel [at] gmail [dot] com
