### ISSUE TITLE
Why not use IoC-container in Mapper->customClassInstance($className) for instancing with constructor injected dependensies?

### ISSUE THREAD

**Issue by likemusic** [analogueorm/analogue#37]
Why not use IoC-container like Illuminate\Container for instancing class with constructor injected dependensies?

In this case, there's no need activator() method in EntityMap. And if the set of Entity use the same service, it is sufficient to define it as a singleton in the settings of the IoC-container.

**Comment by likemusic** [comment]
Implemented but not yet tested here: https://github.com/likemusic/analogue/tree/inject-ioc

**Comment by RemiCollin** [comment]
No that's not an option, as an entity is likely to use the __constructor() method to define its values at creation time : 

```php

class User {

    function __construct($email, $password)
    {
        ...
    }
    ...
}
```

I provided the activator() method to allow the injection of services into a domain object. Note that It's not considered a good pratice though, as you're breaking the DDD principles this way, but I wanted to have this kind of flexibility ;)
