### ISSUE TITLE
Interface `Authenticatable` needs `getAuthIdentifier` on the Entity

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#4]
Somewhere Laravel calls the method `getAuthIdentifier` on the Entity and for now I use this:
```php
class User extends Entity
	public function getAuthIdentifier() {
		return $this->id;
	}
}
```
I noticed that the primary key is defined in the EntityMap.

What's the correct way to get the field name of the primary key inside the Entity?

**Comment by RemiCollin** [comment]
Your code is correct to me. The Entity should not be aware of the EntityMap itself, which is part of the persistence layer. 

I made a separate package for laravel 4 Auth, that I will update to L5 soon : https://github.com/analogueorm/laravel-auth , so you can see how I dealt with it.

**Comment by thasmo** [comment]
I was just wondering how to stay DRY because the primary key is *already* defined on the EntityMap:
https://github.com/analogueorm/analogue/blob/master/src/EntityMap.php#L39

**Comment by RemiCollin** [comment]
How I see it, the getAuthIdentifier method could return another field than the primary key (let's say an uid, or unique() email..) , which can be seen as a responsibility of the Application layer.

Also even if it's a class, conceptualy the entityMap can be seen as a configuration file (which it could have been), so you can argue about the DRY here.

**Comment by thasmo** [comment]
Ow, absolutely - the authentication identifier can be another field of course. I didn't think about that. Thanks for the input!
