### ISSUE TITLE
Add support for tables without primary key

### ISSUE THREAD

**Issue by RiderSx** [analogueorm/analogue#50]
Sometimes in case of handling data in second normal form there comes tables with no need for primary key. But ORM requires primary key to manipulate entities.

My proposal is to add compound keys for such cases.

For example `$primaryKey` may look like this in EntityMap `['good_id', 'bill_id']` and concatenation in subsequent use.

This will grant unique identifier for each entity in table without primary key.

**Comment by RemiCollin** [comment]
I don't think this is worth it, as it would require huge refactoring & added complexity, while having a single integer column inside a table, even if not used, is quite insignificant in term of overhead.

**Comment by RiderSx** [comment]
I can not insist, but my in my situation im not a DB designer and can not do such changes in DB schema. In other case adding column will be a best solution, of course. I will make a fork and add my proposal and you'll decide next accept or not my PR. Thanks for response!

**Comment by RemiCollin** [comment]
I understand. Just be aware that this may prove difficult to implement, due to how analogue internaly tracks entity states in its cache.

**Comment by RiderSx** [comment]
During research finally found the way how you instantiate class w/o calling constructor, awesome trick!

**Comment by RiderSx** [comment]
And yeah, it would be really not easy to implement, just as you said :) Better I'll try to convince DB team to make this change.
