### ISSUE TITLE
Dynamic Relationships Usage

### ISSUE THREAD

**Issue by thasmo** [analogueorm/analogue#6]
The EntityMap provides methods for setting dynamic relationships and I was wondering how the Entity itself copes with those dynamic relationships. E.g. in the documentation example the Entity defines a *hard-coded* method `addComment(Comment $comment)`.

Wouldn't it be neccessary to be able to define dynamic getters and setters on the Entity itself to be able to enjoy the benefits of dynamic relationships for the EntityMap?

Maybe I didn't understand the concept.

Or would one have to implement dynamic getters/setters for dynamically added relationships on their own? Would be awesome if you could provide a small example if you have time! :)

**Comment by RemiCollin** [comment]
The dynamic getters/setters already exist on the Entity itself, so you wouldn't need to implements  more code for dynamic relationships to work.In fact, you could replace the hard-coded function addComment() with $user->comments->add($comment). 

I developped this feature for a plugin driven application I'm working on. It's a mechanism to link core object to extensions, without altering the core code. For example let's say you develop a Forum plugin, you can add a dynamic relationship between the core User entity and a ForumPost entity from the plugin's service provider itself. So it's a very specific use case, but one of the reason behind the developpement of this package, as I couldn't find it in other ORM.

**Comment by thasmo** [comment]
That's brilliant because I was looking for an architecture like this! Perfect fit! :) Thanks for explaining how to use the dynamic relationships on the entity!
