### ISSUE TITLE
[feature request] ability to configure separate folders for entities and entitymaps

### ISSUE THREAD

**Issue by Evertt** [analogueorm/analogue#61]
So simply that analogue has a `config/analogue.php` file in which one can define folders for entities, entitymaps etc...

Right now I'm doing it by putting a loop in my AppServiceProvider to manually register every entitymap I have. It's not pretty. However, I do find my folder structure pretty, which looks a bit like this:

![screen shot 2015-09-21 at 18 29 52](https://cloud.githubusercontent.com/assets/1267282/9998462/8030f710-6091-11e5-82f9-deb3b494aa51.png)

**Comment by RemiCollin** [comment]
Yes I also think this could be a nice feature. We'll need to be able to make it work both in Standalone and Laravel Package version though.

**Comment by Evertt** [comment]
Is it okay for you if I first do the laravel-part and after we merge that then we do the standalone version?

**Comment by RemiCollin** [comment]
Would make more sense the other way round, as we'll probably call a setConfigurationOption() or some similar method on the Manager class, the same way we register plugins.

**Comment by RemiCollin** [comment]
Added in 5.3 , use `Manager::registerMapNamespace()` to add one or several namespace where analogue will look for entityMaps
