### ISSUE TITLE
make everything conform to PSR-2

### ISSUE THREAD

**Issue by Evertt** [analogueorm/analogue#62]
I'm starting to get a bit annoyed by the mixture of tabs-indentation and spaces-indentation in the code.
After we finish up the last pull-requests I'll do it myself. :-)

**Comment by RemiCollin** [comment]
I agree 100%, although I'm rewriting a big part of analogue's internal at the moment which could make merging a mess. I'll try and have it done by tommorow so we can PSR-2 everything then :)

**Comment by Evertt** [comment]
Cool, I look forward to it! :-D
