### ISSUE TITLE
$mapper->newInstance() behaviour

### ISSUE THREAD

**Issue by smallhadroncollider** [analogueorm/analogue#63]
The behaviour of `Mapper::newInstance()` can be pretty confusing if using a custom `__construct` method on an `Entity`.

**Comment by RemiCollin** [comment]
What is confusing about it ? The only use of this method is internally while hydrating entities from a query results. I'll probably move it out the mapper class sooner or later, as it's not intended to be used in client code.

**Comment by smallhadroncollider** [comment]
I thought that might be the case. Probably worth removing from the "Configuring Entity Maps" page:

> TIP : You can get a new instance of your entities by invoking the newInstance() method on the mapper object.

**Comment by RemiCollin** [comment]
This tip was in the context of the activator() method, but you're right it's pretty confusing. I removed it from the wiki. Thanks for pointing it out ;)
