### ISSUE TITLE
[feature request] to have a factory for database seeding in laravel

### ISSUE THREAD

**Issue by Evertt** [analogueorm/analogue#64]
In laravel, with eloquent, you get a nice factory with which you can very easily create new entities with random data. It would be nice to have a Analogue version of that as well.

**Comment by RemiCollin** [comment]
Had a quick look inside laravel source code, I may be wrong but it seems the Factory Builder is hard coded : https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/DatabaseServiceProvider.php

**Comment by Evertt** [comment]
I think you're right. Which doesn't mean we can't work around that, but unfortunately it does mean that we can't do it in the most clean / pretty way. :-\

**Comment by RemiCollin** [comment]
Well, we could always suggest the possibility to resolve the FactoryBuilder from the IoC container to laravel/framework .

**Comment by Evertt** [comment]
Yes, good point :-)
I’ll probably do that later today :-)

**Comment by RemiCollin** [comment]
Ok, I thinked a bit about this. I think the best way to go would be not to override the Laravel's FactoryBuilder, for the simple reason one user could be using Eloquent & Analogue inside a single application. 
Also another point of discussion would be, which default directory to use for user's factory ?

**Comment by RemiCollin** [comment]
As it's a laravel 5.1+ functionnality, I added it as an optionnal package not to break backward compatibility. 

https://github.com/analogueorm/factory

**Comment by smallhadroncollider** [comment]
Is it worth closing this issue now it's done?
