### ISSUE TITLE
[discussion] I wonder if very pure DDD is really the best goal to pursue

### ISSUE THREAD

**Issue by Evertt** [analogueorm/analogue#69]
The reason I wonder this is because it makes so many convenient methods impossible. I just found out that of course the mapper doesn't offer a `firstOrCreate()` method and it's also not really possible to add it, because that would mean skipping the `__construct()` method which means jeopardizing the entity's integrity.

So I'm starting to think that analogue is making development less convenient in name of some pretty principle. How do you see that?

**Comment by RemiCollin** [comment]
The goal of Analogue isn't about making development less convenient, or making every developper follow DDD or even SOLID principles.

The goal is to give the developper the freedom to implement his models/entities in whichever ways he likes. The price for this liberty is that we cannot offer the same boilerplate code that would work for every developper, like the eloquent's `firstOrCreate()` method.

I developped Analogue out of frustration of the many things I couldn't do (or which were just hacky, hard to implement) with Eloquent. Stuff like integrity checks with `__construct()`, single table inheritance, setting up table name at runtime, to name a few. 

On the other hand, setting up a `firstOrCreate()` method on a BaseRepository which would extends the Analogue\ORM\Repository is quite easy to do, if you don't use a `__construct` method, or use a generic `__construct(array $attributes)` in your BaseEntity for example. That's the beauty of OOP. And in that sense, when you say, ' making development less convenient', it's quite a subjective statement in my opinion. 

Like I said to you in the other topic, you're free to code your domain/application in whichever way you feel comfortable. My code examples in the docs surely reflect my way of coding, but these are not rules by any mean. 

That said, I gladly welcome any improvement to Analogue that makes the developer's life easier, with the conditions it works in every situation.

**Comment by Evertt** [comment]
Reading your comment, I actually agree with you. I guess it's just become a bit of a habit for me to impose my preferences on everybody by asking they are implemented in a certain package. I'm gonna stop doing that, because I agree with you, adaptability is what matters and Analogue makes that part quite easy.

**Comment by nicobrinkkemper** [comment]
This should be included in the documentation. I'd say the best place to introduce a firstOrCreate method is the UserRepository. This is really useful for a login/create account feature, so it's going to be the first thing people need to solve. IMO it could be added to the simple ACL tutorial for good measure.
