### ISSUE TITLE
5.1.7: CollectionProxy->count() Error

### ISSUE THREAD

**Issue by smallhadroncollider** [analogueorm/analogue#74]
Only seems to affect 5.1.7.

When I run `$someCollection->count()` I get the following error:

```
ErrorException in CollectionProxy.php line 94: Invalid argument supplied for foreach()

at CollectionProxy->loadOnce() in CollectionProxy.php line 109
```

**Comment by RemiCollin** [comment]
Ok, I see what happens there. https://github.com/analogueorm/analogue/commit/ba44f76f83fa8635ddf94c646a43892e0d310f6c Should fix it
