### ISSUE TITLE
Composite primary key

### ISSUE THREAD

**Issue by Evertt** [analogueorm/analogue#75]
Honestly I haven't actually tested this, but I'm guessing Analogue wasn't made to work with composite primary keys, is that correct?

If that's true, would you like to make it? Or like it if I make it? Because I'd really like this feature. :-)

**Comment by RemiCollin** [comment]
No, composite primary keys are not supported. It would be a fair amount of work to make this happen, and i'm not even sure the Illuminate/Database is capable of handle it. 
I don't mind if you give it a go, just be aware it's not a 2 hours tweak. Probably a full week, at least.

**Comment by Evertt** [comment]
Good to know, thanks. :-)
