### ISSUE TITLE
ErrorException in EntityCollection.php line 9:

### ISSUE THREAD

**Issue by equinoxmatt** [analogueorm/analogue#78]
`Declaration of Analogue\ORM\EntityCollection::max() should be compatible with Illuminate\Support\Collection::max($key = NULL)`

I am receiving this error when trying to complete a find(11).

Any ideas?  Not sure if I am doing something wrong!

**Comment by equinoxmatt** [comment]
Edit:  Using Lumen if that helps.

This seems to affect min(). max() and unique(),  all which are declared in the illuminate\support\collection as $key = null.

Do you want me to submit a pull request, or was this intentional?  Everything works if I add the $key = null into the EntityCollection class.

**Comment by RemiCollin** [comment]
Which version of analogue are you using in composer.json ?

**Comment by equinoxmatt** [comment]
Yep, was still on v2.  My bad! Thank you for all your great work!
