### ISSUE TITLE
Multiple connections issue or better to say feature request

### ISSUE THREAD

**Issue by zoransa** [analogueorm/analogue#8]
Hi guys! I really like this ORM. I have one question... lets say Entity User is at server connection mysql_users and entity Article is on server connection mysql_articles and we make pivot table somewhere on one of those two servers or even 3rd server. Why am I telling you this, some applications really have to scale horizontally by adding servers for different services.

In this case there is no way to do left join, right join... and similar but basically it would be necessary to do separate  queries to get id's from pivot and then data from the other entity similar to eager loading. Can it be done trough ORM instead of doing it manually when we want to do hasMany or belongsToMany.

**Comment by RemiCollin** [comment]
Well, it already works with the limitation the pivot table has to be on the connection the relationship is directed to. eg: If your User entity is the one carrying the relationship, both the user_articles and the articles table would have to be on the mysql_articles connection. (that also mean you cannot define the inverse of the relationship article->users)

HasMany relationships, as they have no pivot, can work both way.

**Comment by zoransa** [comment]
Hi Remi! Thanks for quick answer. Can it be done something to enable two way connection? If we would add connection to the parameters on 'the other side' and few if and slight change on algorithm instead of one query with joins do it 'eager loading' that would be awesome...

If you think it is not something your package should do let me know I will close the ticket.

**Comment by RemiCollin** [comment]
In fact, I have plans for supporting additionnal mapping drivers, with the possibility to build complex objects from several sources (sql, json api,...), which will mean abstracting relationships from SQL at a point. I have absolutely no ETA on this though, but I thought about it a lot recently.

Still, I think your approach might work in the current system. Maybe we could prepend the name of the pivot table with the name of the connection it's on in the relationship method, something like 'connection.pivot_table', then choose the querying method accordingly. I'll look into it when I have some time.

**Comment by zoransa** [comment]
Yes exactly because what I wanted to do is dump 'logs' to mongodb those are infinite files of 
```
user_id, item_id, item_type, action
```
and storing them in main database is just pain... even scaling with additional server leaves open the problem of where to put it. I really like your approach and my advice is to try to run away from 'joints' and treat database almost like 'nosql'
