### ISSUE TITLE
Updating an existing entity with a relationship property doesn't update the foreign key

### ISSUE THREAD

**Issue by smallhadroncollider** [analogueorm/analogue#87]
I have a `Document` entity which links to a `File` using a `belongsTo` relationship:

```php
    public function file(Document $document)
    {
        return $this->belongsTo($document, File::class, "file_id", "id");
    }
```

If I take an existing document and then set `file` to a new `File` entity, when I store the `Document` the `file_id` key does not get updated.

---

The `Document` just before running `store` on it. Afterwards the `file_id` remains `575`, not `581`.

```
Document {#626
  #attributes: array:17 [
    "id" => "487"
    "title" => "Aliquid proident rerum sint ratione ducimus quisquam reprehenderit veniam ad"
    "file_id" => "575"
    "file" => File {#636
      #attributes: array:8 [
        "location" => "documents"
        "id" => 581
        "filename" => "kYQVgWog.pdf"
      ]
    }
  ]
}
```

**Comment by RemiCollin** [comment]
Fixed in https://github.com/analogueorm/analogue/commit/78924a60cd607ff69a5b59fe3926455c90ca6206

**Comment by smallhadroncollider** [comment]
Great, thanks.

**Comment by RemiCollin** [comment]
Analogue definitely needs a more robust test suite. This was the first one I wrote, now I'd just like to rewrite it from scratch once I have time.
I'm on the hunt for the other bug concerning the belongsToMany relationships, it seems to be a cache issue.

**Comment by smallhadroncollider** [comment]
Yeah, I think a more robust test suite would be good. The bugs I did manage to fix were all just little typos - nothing wrong with the logic/functionality, just passing the wrong object or using a method on the wrong object.

**Comment by smallhadroncollider** [comment]
Let me know if I can be of any help. I try to keep some time free most weeks to work on side-projects. And I'm using Analogue for most my paid work, so it's in my interests to get it as stable as possible.

**Comment by RemiCollin** [comment]
Well, you're already helping and very welcome to ! I'd love to have more time to work on analogue but these days i have less free time than i used to. 

I guess the next steps will be to transfer documentation to a git repo (I have a design nearly done to push it to transfer it github.io webpage), update it quite a bit, and rewrite the test suite from scratch, probably using Illuminate/Foundation/Testing & the new Analogue/Factory package as helpers.
